name: maven_hw_ci

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - name: Run build script
        run: ./versioning.sh
        shell: bash
