name: maven_hw_ci

on:
  push:
    branches: [ "workflow_ci" ]
    
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
    - name: Connect to Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  
        token: ${{ github.token }}
    - name: Run build script
      run: ./versioning.sh
      shell: bash
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DH_UN }}
        password: ${{ secrets.DH_AC }}
    - name: set tag to env
      run: |
        ls -la
        cat /myapp/.version
    # - name: Build image and push to Docker Hub and GitHub Container Registry
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: 
    # VER=$(cat /myapp/.version)
    # echo "VER=${VER}" >> $GITHUB_ENV
    # echo $VER