name: maven_hw_ci

on:
  push:
    branches: [ "workflow_ci" ]

  workflow_dispatch:

jobs:
  maven_hw: 
    runs-on: ubuntu-20.04
    environment: dh_u
    steps:

    - name: Connect to Repo
      uses: actions/checkout@v3

    - name: Versioning stage
      run: |
        # get last version from Dockerhub
        VERSION=$(curl -s https://registry.hub.docker.com/v2/repositories/danieliko/${DH_REPO}/tags/ | jq '.results[0].name')

        # use python to remove double quotes from version
        VERSION=$(python3 -c " 
        VERSION=$VERSION.replace('\"', '') 
        print(VERSION) ")

        # increment by 0.0.1
        VERSION=$(echo ${VERSION} | awk -F. -v OFS=. '{$NF += 1 ; print}')       
        
        # export to github env and create a tag for Docker image
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        TAG="danieliko/maven-hw-testings:$(echo $VERSION)"
        echo "TAG=${TAG}" >> $GITHUB_ENV

    - name: Set up Docker Buildx # Enable using docker on pipeline
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DH_UN }}
        password: ${{ secrets.DH_AC }}

    - name: Build image and push to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        build-args: VERSION=${{ env.VERSION }}
        tags: ${{ env.TAG }}


    - name: Run the image
      run: docker run ${{ env.TAG }}