name: maven_hw_ci

on:
  push:
    branches: [ "workflow_ci" ]
    
  workflow_dispatch:

jobs:
  CI:
    - name: Connect to Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ github.token }}
    runs-on: ubuntu-20.04
    steps:
      - name: Run build script
        run: ./versioning.sh
        shell: bash
